language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy
  - pypy3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install tox-travis coveralls flake8
script:
  - flake8
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Algosec
  password:
    secure: oWwAfP7BDBcSq19zff/mc9xQkIOEA3GWb6Xa82JixfqasOYA1bR5zHM/DQNHTStuabp4H3c5K/9j02shOQal66MlDjcaGGugWY1be62oxCoegFhJaTI+b5ujt+K/nHoUulqv+PaIQXHzhvHl4nRS4IXVJL8yuU6sip+2sVRZhkx5P11CQ/d3OFGwUbXxM+cSPPd1zHTqXkn8/Lwkipd8bSIRgNopVu9HdbXslwVX0MrzkKptNjR9E8bt7vHOtFWaxOfKvP0zVOzpaAKiTLqUrWejLpRHx0H9b0IofsLn7C9aGRPWM4L2vJVpb9quj3ekmR9Qe2axm3yLoeYiuV1MRiFiGpXbFhUuBQwsHHPGZAfsBUA3jl9YDNpZiQrZfgwFMMUc0CG4U1kA8NJZ050INujaWGkji8M+xuU1o/XgJtXJ4LBQu3P1fhrbi3IeGdDK+DyQ1koovGedTPnxFRSHzvc7EeLmqgGUwFKNYEcu1NvCl9YU7CVDeBMWxRvbow348ahESEFbEMlwY1Ym5+SVDbvZIxR62HRbv6LlsixdoZgTzKqG3v/px7XAs/sn/O1tb+AdU0hBQQKM4WNm1sb2bOLuhXmMQDKSQYdnnwdCaXYSV1lBvWms9HA+TsUKDCCdKgAteiRkv8G1o10amLkgGaFMvRTFK8DgI0e4nJI/nDc=
  on:
    tags: true
    repo: algosec/algosec-python
    python: 3.6
notifications:
  email:
    on_success: never
    on_failure: always
