language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy
  - pypy3.5
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install tox-travis codecov flake8
script:
  - flake8
  - tox
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: algosec
  password:
    secure: W5p8f3+F4hKtxGoYtm6qsakPFSBePCg8efoTuky+QVOS4BR+bFjHhd+Kxu4+msjmEWJhZ4gWmeFV+stDcnPimVNi4hqj0znR6QqD+9ND4RZ566llEoUJ2MNXQdYBA/M/g+m18tvoytVXk32YwwlgPtf2dMKyMKvbXUGitc3nGtlS7ReX1XRWJa++uS0rskyRz5tc4jK2awde8edVWVe5g6gf5j3f9507WFbluK3X4YaH/70Q4kKnJx2m9CCxXXSca8ZtuFg+EYGjSi1tMiBqyKmNgph876xEIuQnztYAWY5sh3QCt2ZBz5/ZtcGQem+qJK0ektloRU2qwMvDx9GI3Wcy88b5c4J4E0tKyEoVAZXQdlhqH/n7wjUZqHee/q3/fDDcn4nzcBDJHXfSVTgWRgUfpX0SIsBHkdIzdUIbATKelbh+NVnd3jiW3oOMipOFclUtQAVJWueJtG6VBKBA1TAqJ5iWP/MBlXzZNo7asrQv8pR5sFL3KeA5Hk7JO7WFaDNj0njeJGBvo+YYsHVE6CDYjB1GRUmyc5l0B8fCfRRuxKWOkwr76bCndIedkCJd5bIfHAF5gVHxv3VV9l8HrGgJ2Xa0r3efrkBL1R8U+edkdNR74mppkpKnlk0HZ0OwjqVYVoE0VS6QzbibL+aC9ImYDde4sQPkaYoB75HMBA4=
  on:
    tags: true
    repo: algosec/algosec-python
    python: 3.6
notifications:
  email:
    on_success: never
    on_failure: always
