language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3.5'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=deploy
# command to install dependencies
install:
  - pip install tox-travis coveralls flake8
# command to run tests
script:
  - flake8
  - tox
after_success:
  - coveralls
# Automatically deploy new tagged versions to PyPi
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: Algosec
  password:
    secure: MTSZ3MbHTix8Jd2b1/Wn+xgnFdfARAM0R5nJxMgJlb3OXmZkphj9ggErsiU/3wx943vSdulpUp0m5KXcvvQ06zF4eCwfgguXHaqay/YFFNCE2CB7nKfV+gpal+8AWA5g5DFG/02UqxlFO25kp/rutT0s5aR8Oe3td+N62dncnZhDWSDV/Fvv6e+4blKjVVcyYNJxV5T2zf341QaWDFVfGGV7KAohdIU4KComjE/KMRmEOyginpYRytZ9HxOmjEJ1EjOFWLLq99wQcWuOVF0HfrW8VmJ70+diFt6pnGBV2DQKrs8ij7NdpM84WHX+rbfAdBRThM/4mTEaxwmbHR4cWIBWLkMJ9s6ZtSdpG8Wb1qO97esY3r1c14W08FyhJrNN1QHdRVH2GE9KM40V0xXuwEJOQUKONElVHRUvZqoDXxXwv6lIFDriuqVK8DidM4FKMIoYLTOtBnnz/5SciTmzGM0S9NCCwhp5+vbzKOyuYGPGVAGok4sEyGPeCC1pX+wc5Zyg98ppvp54J0wZ0uwagJl7hHAdvx0hYEJmgqvAWQzDGYUyPT07pM1s5CYVilhRgUGypfNvjkHc6oDJBi651WI0KSh3+YvB6pBpyM38JMauhNmqTG/7E+yeydmqLXuOaP2etXG+OfmINiQmMIlTsFqFv+aIzT8bSqZFwyX/sqA=
  on:
    tags: true
    branch: master
    condition: "$TOXENV = deploy"
branches:
  # Trigger build only for master, the rest should use PRs for builds to work
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always
