language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Get 3.7 here when travis add support for it https://github.com/SoCo/SoCo/pull/628
#  - "3.7"
# command to install dependencies
install:
  - pip install tox-travis coveralls
# command to run tests
script:
  - tox
after_success:
  - coveralls